# Site settings
title: Coding Journey
header-img: img/home-bg.png
email: contact.vandepool@gmail.com
copyright_name: jenpoole
description: > # this means to ignore newlines until "baseurl:"
  Learning Web Development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jenpoole
learn_profile: jenpoole
email_username: contact.vandepool@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
